services:
  db:
    image: postgres:16
    container_name: marketly_db
    environment:
      POSTGRES_USER: marketly
      POSTGRES_PASSWORD: marketly
      POSTGRES_DB: marketly
    ports:
      - "5432:5432"
    volumes:
      - marketly_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marketly -d marketly"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: marketly_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # IMPORTANT: inside docker, DB host is the service name "db"
      DATABASE_URL: postgresql+psycopg2://marketly:marketly@db:5432/marketly
    ports:
      - "8000:8000"
    volumes:
      # lets you edit code locally and auto-reload if you use reload CMD
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  marketly_pgdata:
