services:
  # db:
  #   image: postgres:16
  #   container_name: marketly_db
  #   environment:
  #     POSTGRES_USER: marketly
  #     POSTGRES_PASSWORD: marketly
  #     POSTGRES_DB: marketly
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - marketly_pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U marketly -d marketly"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_JWT_SECRET=${SUPABASE_JWT_SECRET}
    volumes:
      - ./:/app


volumes:
  marketly_pgdata:
